
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#6CE6DB")


canvas = Canvas(
    window,
    bg = "#6CE6DB",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    643.6068420410156,
    496.31819152832037,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=391.2441711425781,
    y=459.9419250488282,
    width=504.725341796875,
    height=70.75253295898438
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    643.6068420410156,
    372.808090209961,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#00353F",
    highlightthickness=0
)
entry_2.place(
    x=391.2441711425781,
    y=336.4318237304688,
    width=504.725341796875,
    height=70.75253295898438
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    641.5458068847656,
    250.98989105224615,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_3.place(
    x=389.1831359863281,
    y=214.6136322021485,
    width=504.725341796875,
    height=70.75251770019531
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=590.0,
    y=578.0,
    width=100.0,
    height=100.0
)

canvas.create_text(
    388.0,
    426.00000000000006,
    anchor="nw",
    text="Keypath",
    fill="#1E1E1E",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    388.0,
    304.00000000000006,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    388.0,
    183.00000000000006,
    anchor="nw",
    text="Username",
    fill="#1E1E1E",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    494.0,
    143.00000000000006,
    anchor="nw",
    text="Glad to see you here ; )",
    fill="#00353F",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    456.0,
    58.00000000000006,
    anchor="nw",
    text="Hey There!",
    fill="#000000",
    font=("Poppins ExtraBold", 64 * -1)
)
window.resizable(False, False)
window.mainloop()
