
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#6CE6DB")


canvas = Canvas(
    window,
    bg = "#6CE6DB",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    643.0,
    477.00000000000006,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#00353F",
    highlightthickness=0
)
entry_1.place(
    x=388.0,
    y=436.00000000000006,
    width=510.0,
    height=80.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    643.0,
    291.00000000000006,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_2.place(
    x=388.0,
    y=250.00000000000006,
    width=510.0,
    height=80.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=590.0,
    y=578.0,
    width=100.0,
    height=100.0
)

canvas.create_text(
    385.0,
    400.00000000000006,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    387.0,
    215.00000000000006,
    anchor="nw",
    text="Username",
    fill="#1E1E1E",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    494.0,
    143.00000000000006,
    anchor="nw",
    text="Welcome Back!",
    fill="#00353F",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    456.0,
    58.00000000000006,
    anchor="nw",
    text="Login",
    fill="#000000",
    font=("Poppins ExtraBold", 64 * -1)
)
window.resizable(False, False)
window.mainloop()
