
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#6CE6DB")


canvas = Canvas(
    window,
    bg = "#6CE6DB",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    719.0,
    554.0,
    anchor="nw",
    text="View Saved Password",
    fill="#1E1E1E",
    font=("Poppins ExtraBold", 32 * -1)
)

canvas.create_text(
    78.0,
    553.0,
    anchor="nw",
    text="Store New Passwords",
    fill="#1E1E1E",
    font=("Poppins ExtraBold", 32 * -1)
)

canvas.create_text(
    240.0,
    47.00000000000006,
    anchor="nw",
    text="Hey There, {username}!",
    fill="#000000",
    font=("Poppins ExtraBold", 64 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=145.0,
    y=185.00000000000006,
    width=350.0,
    height=350.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=785.0,
    y=193.00000000000006,
    width=350.0,
    height=350.0
)
window.resizable(False, False)
window.mainloop()
