
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#6CE6DB")


canvas = Canvas(
    window,
    bg = "#6CE6DB",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    641.0,
    336.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=397.0,
    y=293.0,
    width=488.0,
    height=84.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    640.0,
    488.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#00353F",
    highlightthickness=0
)
entry_2.place(
    x=396.0,
    y=445.0,
    width=488.0,
    height=84.0
)

canvas.create_text(
    399.0,
    407.0,
    anchor="nw",
    text="Site Password",
    fill="#000000",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    399.0,
    258.0,
    anchor="nw",
    text="Site Name",
    fill="#1E1E1E",
    font=("Poppins ExtraBold", 24 * -1)
)

canvas.create_text(
    196.0,
    118.0,
    anchor="nw",
    text="Enter Site Details below",
    fill="#000000",
    font=("Poppins ExtraBold", 64 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=565.0,
    y=565.0,
    width=150.0,
    height=150.0
)
window.resizable(False, False)
window.mainloop()
